import { createSlice } from "@reduxjs/toolkit";

export const languageSlice = createSlice({
  name: "language",
  initialState: {
    words: {
      en: {
        sample: "SAMPLE",
        clear_all: "CLEAR ALL",
        pdf: " Download PDF",
        live_edit: "LIVE EDIT",
        import: "IMPORT",
        export: "Save",
        primary: "Primary",
        secondary: "Secondary",
        title: "Main Title",
        subtitle: "Subtitle",
        titles: "Titles",
        textLeft: "Text 1",
        textRight: "Text 2",
        add: "ADD",
        clear: "CLEAR",
        personal_information: "Personal Information",
        social: "Social",
        languages: "Languages",
        hobbies: "Hobbies",
        education: "Education",
        experience: "Experience",
        skills: "Skills",
        projects: "Projects",
        courses: "Courses",
        references: "References",
        social_upper: "SOCIAL",
        languages_upper: "LANGUAGES",
        hobbies_upper: "HOBBIES",
        education_upper: "EDUCATION",
        experience_upper: "EXPERIENCE",
        skills_upper: "SKILLS",
        projects_upper: "PROJECTS",
        courses_upper: "COURSES",
        references_upper: "REFERENCES",
        name_surname: "Full Name",
        form_title: "Title",
        photo: "Photo",
        address: "Address",
        phone_number: "Phone Number",
        email_address: "Email Address",
        about: "About",
        twitter_username: "Twitter Username",
        github_username: "Github Username",
        linkedin_username: "LinkedIn Username",
        personal_website: "Personal Website",
        external_url: "External URL",
        username_or_url: "Username or URL Address",
        select: "Select",
        language: "Language Name",
        native: "Native Language",
        hobby: "Hobby Name",
        school: "Institute Name",
        subject: "Subject",
        degree: "Degree",
        city: "City",
        from: "From",
        to: "To",
        company: "Company Name",
        position: "Position",
        description: "Description",
        skill: "Skill Name",
        level: "Level",
        project: "Project Name",
        link: "Project Link",
        course: "Course Name",
        reference: "Reference Name",
        reference_title: "Reference Title",
        confirm: "Are you sure all data will be deleted?",
    
      },
    },
    language: "en",
  },
  reducers: {
    setLanguage: (state, action) => {
      state.language = action.payload;
    },
  },
});

export const { setLanguage } = languageSlice.actions;

export default languageSlice.reducer;
